version: "3.7"

services:
  chii-redis:
    container_name: "chii-redis"
    image: redis:7
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass "redis_password"
    restart: always

  chii:
    container_name: "chii-web-server"
    image: ghcr.io/bangumi/chii:latest
    command: [web]
    restart: always
    ports:
      - "3000:3000"
    network_mode: host
    environment:
      HTTP_PORT: "3000"
      MYSQL_HOST: "mysql"
      MYSQL_PORT: "3306"
      MYSQL_DB: "bangumi"
      MYSQL_USER: "mysql_user"
      MYSQL_PASS: "mysql_password"
      REDIS_URI: "redis://:redis_password@chii-redis:6379/0"
      WEB_DOMAIN: "next.bgm.tv"
      MYSQL_MAX_CONNECTION: "4"
      MEILISEARCH_URL: "http://meilisearch:7700"
      MEILISEARCH_KEY: "$master-key"

  chii-canal:
    container_name: "chii-app-canal"
    image: ghcr.io/bangumi/chii:latest
    restart: always
    command: [canal]
    environment:
      HTTP_PORT: "2000" # metrics
      KAFKA_BROKER: "..."

  mysql:
    # 需要从 https://github.com/bangumi/dev-env 手动导入所有的数据表定义，后端服务器不会自动初始化数据库。
    container_name: "chii-mysql"
    image: "mysql:5.7.33"
    command: mysqld --character-set-server=utf8mb4
    environment:
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysql_password
      - MYSQL_DATABASE=bangumi

  meilisearch:
    container_name: "chii-meilisearch"
    image: "getmeili/meilisearch:v1.0"
    command: meilisearch --env production
    environment:
      MEILI_ENABLE_METRICS_ROUTE: "true"
      MEILI_MASTER_KEY: "$master-key"
      MEILI_LOG_LEVEL: "WARN"
    ports:
      - "127.0.0.1:7700:7700"
    volumes:
      - ./data/meili_data:/meili_data/

  kafka:
    # you also need a zookeeper
    container_name: "chii-base-kafka"
    image: confluentinc/cp-kafka:7.3.1
    # set full config as you needed

  debezium-server:
    container_name: chii-debezium
    image: debezium/server:2.2
    environment:
      # set full config as you needed
      - "JAVA_OPTS=-Xms256m -Xmx1536m"
      - "debezium.sink.type=kafka"
      - "debezium.source.snapshot.mode=schema_only"
      - "debezium.source.snapshot.locking.mode=none"
      - "debezium.source.table.include.list=bangumi.chii_members,bangumi.chii_subjects,bangumi.chii_subject_fields"
      - "debezium.source.schema.history.internal.kafka.topic=debezium.history"
      - "debezium.source.schema.history.internal.kafka.bootstrap.servers=kafka:9092"
      - "debezium.source.topic.prefix=debezium.chii"
