name: Lint Other Language

on:
  push:
    branches:
      - master
    paths:
      - "**.md"
      - "**.py"
      - "**.yaml"
      - "**.yml"
      - "**.html"
      - "**.json"
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - master
    paths:
      - "**.md"
      - "**.py"
      - "**.yaml"
      - "**.yml"
      - "**.html"
      - "**.json"

jobs:
  lint-other:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node LTS
        uses: actions/setup-node@v2

      - run: npm i -g prettier

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Checkout code
        uses: actions/checkout@v3
        if: ${{ github.event_name != 'push' }}
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: Checkout code
        uses: actions/checkout@v3
        if: ${{ github.event_name == 'push' }}

      - name: prettier
        run: prettier --write --list-different ./

      - run: git diff --exit-code

      - name: create review
        if: ${{ failure() && github.event_name != 'push' }}
        run: |
          TMPFILE=$(mktemp)
          git diff >"${TMPFILE}"
          git reset --hard HEAD

          reviewdog -f=diff -f.diff.strip=1 -reporter=github-pr-review -tee < "${TMPFILE}"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
