name: Lint Other Language

on:
  push:
    branches-ignore:
      - renovate/**
    paths:
      - "**.md"
      - "**.js"
      - "**.yaml"
      - "**.yml"
      - "**.html"
      - "**.json"
  pull_request:
    branches:
      - master
    paths:
      - "**.md"
      - "**.js"
      - "**.yaml"
      - "**.yml"
      - "**.html"
      - "**.json"

jobs:
  lint-other:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node LTS
        uses: actions/setup-node@v3

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Checkout code
        uses: actions/checkout@v3

      - run: npm ci

      - name: prettier
        run: npm run format

      - run: git diff --exit-code

      - uses: reviewdog/action-suggester@v1
