name: Rust CI

on:
  push:
    branches:
      - master
  merge_group:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-lint:
    runs-on: ubuntu-24.04
    env:
      TARGET: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ env.TARGET }}

      - name: Check format
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --workspace --all-targets --locked

  rust-test:
    runs-on: ubuntu-24.04
    env:
      TARGET: x86_64-unknown-linux-gnu
    steps:
      - run: git clone https://github.com/bangumi/dev-env $HOME/dev-env --branch=gh-pages
      - run: cd ~/dev-env && docker compose up -d

      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ env.TARGET }}

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - run: bash $HOME/dev-env/wait_mysql_ready.sh

      - name: Run tests
        run: cargo nextest run --workspace --locked
        env:
          RUST_MYSQL_DSN: mysql://user:password@127.0.0.1:3306/bangumi
          MYSQL_DSN: mysql://user:password@127.0.0.1:3306/bangumi

  docker:
    runs-on: ubuntu-24.04
    needs: [rust-lint, rust-test]
    env:
      TARGET: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ env.TARGET }}

      - name: Build release binary
        run: cargo build --release --locked --target $TARGET -p app

      - name: Build rust docker image
        run: docker build --build-arg TARGET=$TARGET -t app-rust -f etc/Dockerfile.rust .

      - name: Smoke run
        run: docker run --rm app-rust --help
